2023-12-31 11:59:59,908 INFO "GET /news/ HTTP/1.1" 200 5766 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 11:59:59,964 WARNING "GET /static/css/styles.css HTTP/1.1" 404 1801 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 11:59:59,985 WARNING Not Found: /apple-touch-icon-precomposed.png /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py None 
2023-12-31 11:59:59,985 WARNING "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2497 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 11:59:59,990 WARNING Not Found: /apple-touch-icon.png /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py None 
2023-12-31 11:59:59,991 WARNING "GET /apple-touch-icon.png HTTP/1.1" 404 2461 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 12:00:00,027 WARNING Not Found: /favicon.ico /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py None 
2023-12-31 12:00:00,028 WARNING "GET /favicon.ico HTTP/1.1" 404 2434 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 12:00:05,580 ERROR Internal Server Error: /news/ /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py (<class 'django.core.exceptions.FieldError'>, FieldError("Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title"), <traceback object at 0x7f904038eb00>) 
Traceback (most recent call last):
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/project/news/views.py", line 55, in get_queryset
    return self.filterset.qs
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 230, in qs
    qs = self.filter_queryset(qs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 213, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 179, in filter
    return super().filter(qs, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 158, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title
2023-12-31 12:00:05,599 ERROR "GET /news/?title__icontains=&dateCreation__day=&Categorytype=2&PostTitle= HTTP/1.1" 500 158733 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 12:00:21,064 ERROR Internal Server Error: /news/ /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py (<class 'django.core.exceptions.FieldError'>, FieldError("Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title"), <traceback object at 0x7f904044ca00>) 
Traceback (most recent call last):
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/project/news/views.py", line 55, in get_queryset
    return self.filterset.qs
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 230, in qs
    qs = self.filter_queryset(qs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 213, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 179, in filter
    return super().filter(qs, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 158, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title
2023-12-31 12:00:21,075 ERROR "GET /news/?title__icontains=&dateCreation__day=&Categorytype=2&PostTitle=2 HTTP/1.1" 500 158742 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
2023-12-31 12:00:29,449 ERROR Internal Server Error: /news/ /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/utils/log.py (<class 'django.core.exceptions.FieldError'>, FieldError("Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title"), <traceback object at 0x7f904036de40>) 
Traceback (most recent call last):
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/project/news/views.py", line 55, in get_queryset
    return self.filterset.qs
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 230, in qs
    qs = self.filter_queryset(qs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filterset.py", line 213, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 179, in filter
    return super().filter(qs, value)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django_filters/filters.py", line 158, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'postCategory' into field. Choices are: author, author_id, category, categoryType, category_id, comment, dateCreation, id, rating, text, title
2023-12-31 12:00:29,462 ERROR "GET /news/?title__icontains=w&dateCreation__day=1&Categorytype=2&PostTitle=2 HTTP/1.1" 500 144928 /Users/natalakulikova/PycharmProjects/pythonProject5/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py None 
